language: python3

before_install:
- sudo apt-get install python-sphinx
- sudo apt-get install python3-setuptools 

install:
- python3 setup.py install --user
- ( cd doc && make html )

script: pytest -vv 

