language: python

python:
- "3.3"
- "3.4"
- "3.5"
- "3.6"

before_install:
- sudo apt-get install python-sphinx
- pip install --user alabaster
- pip install --user --upgrade sphinx
- pip install --user pytest
- pip install --user pytest-cov

install:
- ( cd doc && make html )

script: pytest --cov=ljson --cov-report=term-missing  -vv 

notifications:
        webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
