language: python

python:
- "3.3"
- "3.4"
- "3.5"
- "3.6"

before_install:
- sudo apt-get install python-sphinx
- sudo apt-get install python3-setuptools 
- sudo apt-get install python3-pip
- sudo python3 -m pip install alabaster
- sudo python3 -m pip install --upgrade sphinx
- sudo python3 -m pip install pytest
- sudo python3 -m pip install pytest-cov

install:
- python3 setup.py install --user
- ( cd doc && make html )

script: pytest --cov=ljson --cov-report=term-missing  -vv 

notifications:
        webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
